version: "3.7"

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - /mnt/db:/var/lib/mysql
    secrets:
      - wp_db_password
      - mysql_root_password
    environment:
      - MYSQL_USER=testuser
      - MYSQL_DATABASE=testdb
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    networks:
        - private
    # command: "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--wait_timeout=28800", "--interactive_timeout=28800", "--max_allowed_packet=256M"]
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s

  wordpress:
    image: wordpress:latest
    # volumes:
    #   - /mnt/wp:/..
    networks:
      - private
    network:
      - public
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: wpcluster_poc
      WORDPRESS_DB_NAME: testdb
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s

secrets:
  wp_db_password:
    external: true
  mysql_root_password:
    external: true
volumes:
  db:
    driver: "local"
  wp:
    driver: "local"
networks:
  private:
    external: true
