version: "3.7"

services:

  wordpress:
    image: wordpress:php7.4
    volumes:
      - /mnt/wp:/var/www/html/wp-content
    networks:
      - wpcnet
    secrets:
      - wp_db_password
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=testuser
      - WORDPRESS_DB_NAME=testdb
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_db_password
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  mariadb:
    image: mariadb:10.5.8
    volumes:
      - /mnt/db:/var/lib/mysql
    secrets:
      - wp_db_password
    environment:
      - MYSQL_USER=testuser
      - MYSQL_DATABASE=testdb
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_db_password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - wpcnet
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  haproxy:
    image: haproxytech/haproxy-debian:2.3
    volumes:
      - ./conf/:/etc/haproxy/:ro
      - ./certs:/usr/local/etc/certs:ro
    networks:
      - wpcnet
    ports:
      - "80:80"
      - "443:443"
    dns:
      - "127.0.0.11"
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

  nginx-certbot:
    image: nginx
    volumes:
      - ./webroot:/usr/share/nginx/html
    networks:
      - wpcnet
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

secrets:
  wp_db_password:
    external: true
volumes:
  db:
    driver: "local"
  wp:
    driver: "local"
networks:
  wpcnet:
    external: false
